In [ ]:
import os
from ambry.bundle import BuildBundle
b = BuildBundle(os.getcwd())

In [28]:
df = b.partitions.find(table ='pdd_summary_mdc').pandas
dfmi = df.set_index(['oshpd_id','year','mdc'])
dfmi = dfmi.drop('id',1).unstack().fillna(0)
dfmi.to_csv('count_by_mdc.csv')

In [74]:
p = b.library.dep('pddpuf').partition

q = "SELECT id, oshpd_id, dschyear as year,  msdrg FROM pdd_puf_c WHERE mdc = '14'"

df = p.select(q).pandas
dfx = df.groupby(['oshpd_id','year','msdrg']).count().unstack().fillna(0)
dfx

               id                                         ...               \
msdrg         001 003 004 005 014  765   766  767 768 769 ... 780  781 782
oshpd_id year                                             ...
10735    2010   0   0   0   0   0    0     0    0   0   0 ...   0    6   0
         2011   0   0   0   0   0    0     0    0   0   2 ...   0    5   0
         2012   0   0   0   0   0    0     0    0   0   1 ...   0    3   0
         2013   0   0   0   0   0    0     0    0   0   1 ...   0    5   0
10739    2010   0   0   1   0   0  960  1135  234   2  29 ...  16  362  90
         2011   0   0   0   0   0  951   928  261   3  18 ...  26  373  95
         2012   0   0   0   0   0  879   922  230   3  21 ...  26  335  88
         2013   0   0   0   0   0  906   892  206   4  16 ...  38  325  87
10776    2011   0   0   0   0   0    0     0    0   0   0 ...   0    0   0
10805    2010   0   0   0   0   0   98   275   12   0  10 ...   0   55   4
         2011   0   0   0   0   0  129   236   13   1   5 ...   1   44   5
         2012   0   0   0   0   0  112   262   13   0   6 ...   2   45  10
10844    2010   0   0   0   0   0    0     0    0   0   0 ...   0   29   0
         2011   0   0   0   0   0    0     0    0   0   0 ...   0   14   0
         2012   0   0   0   0   0    0     0    0   0   0 ...   0   15   0
         2013   0   0   0   0   0    0     0    0   0   0 ...   0   13   0
10846    2010   0   0   0   0   0  105   209   68   0   4 ...  10  144  36
         2011   0   0   0   0   0   95   179   54   0   3 ...   6  109  27
         2012   0   0   0   0   0  112   192   39   1   3 ...   8  124  29
         2013   0   0   0   0   0  120   202   39   0   3 ...  11  147  38
10856    2010   0   0   0   0   0  350   251    5   3   8 ...   9  106  19
         2011   0   0   0   0   0  406   241    6   2  11 ...   7  101  27
         2012   0   0   0   0   0  433   232   12   6   8 ...   4  122  27
         2013   0   0   0   0   0  421   258   10   1  10 ...   8   96  21
10858    2010   0   0   0   0   0  350   394    7   2   8 ...   7   96  22
         2011   0   0   0   0   0  380   408    6   1  12 ...   2   89  20
         2012   0   0   0   0   0  369   340    3   3   5 ...   6   86  16
         2013   0   0   0   0   0  406   387    7   2   8 ...   1   66   9
10937    2010   0   0   0   0   0    0     0    0   0   0 ...   0   13   0
         2011   0   0   0   0   0    0     0    0   0   3 ...   0    6   3
...            ..  ..  ..  ..  ..  ...   ...  ...  ..  .. ...  ..  ...  ..
560492   2012   0   0   0   0   0  175   468   16   4   6 ...   3   65  27
         2013   0   0   0   0   0  212   491   23   1   2 ...   5   55  25
560501   2010   0   0   0   0   0    0     0    0   0   0 ...   0    1   0
         2011   0   0   0   0   0    0     0    0   0   0 ...   0    1   0
         2012   0   0   0   0   0    0     0    0   0   0 ...   0    0   0
560508   2010   0   0   0   0   0   10    53    0   0   3 ...   1    8   4
         2011   0   0   0   0   0   11    42    2   0   5 ...   0    9   3
         2012   0   0   0   0   0    8    40    0   0   2 ...   1    4   0
         2013   0   0   0   0   0    0     0    0   0   0 ...   0    1   0
560525   2010   0   0   0   0   0   58   153    2   0   3 ...   7   26   6
         2011   0   0   0   0   0   71   142    3   0   0 ...   2   25   8
         2012   0   0   0   0   0   70   148    3   0   4 ...   1   28   4
         2013   0   0   0   0   0   58   127    0   0   1 ...   4   30   5
560529   2010   0   0   0   0   0  200   379    9   0   3 ...  15  149  44
         2011   0   0   0   0   0  272   520    8   0   7 ...  19  121  37
         2012   0   0   0   0   0  350   513    4   0  12 ...  13  136  49
         2013   0   0   0   0   0  305   515    2   0   6 ...  23   96  32
564121   2010   0   0   0   0   0    0     0    0   0   0 ...   0    0   0
571086   2010   0   0   0   0   0   47   113   44   0   4 ...   0   26   5
         2011   0   0   0   0   0   49    97   40   1   4 ...   1   23  10
         2012   0   0   0   0   0   61   100   33   1   0 ...   1   31   4
         2013   0   0   0   0   0   69   105   41   0   4 ...   0   29   7
574010   2010   0   0   0   0   0   84   154   24   1   3 ...  10   26  13
         2011   0   0   0   0   0  102   125   24   1   7 ...   5   36  14
         2012   0   0   0   0   0  109   142   16   0   4 ...   7   24  13
         2013   0   0   0   0   0   93   146   29   0   7 ...   6   32  17
580996   2010   0   0   0   0   0  145   437   98   1   8 ...   5   63  16
         2011   0   0   0   0   0  167   467   94   1   5 ...   8   68  26
         2012   0   0   0   0   0  157   435   92   1  11 ...   5   81  15
         2013   0   0   0   0   0  182   413   72   1   2 ...   2   71  12


msdrg         981 982 983 987 988 989 998
oshpd_id year
10735    2010   0   0   0   0   0   0   0
         2011   0   0   0   0   0   0   0
         2012   0   0   0   0   0   0   0
         2013   0   0   0   0   0   0   0
10739    2010   0   1   0   1   2   0   0
         2011   0   1   0   1   0   0   0
         2012   3   0   0   0   2   1   0
         2013   0   0   0   1   0   0   1
10776    2011   0   0   0   0   0   0   0
10805    2010   0   0   0   0   0   0   0
         2011   0   0   0   0   0   0   0
         2012   0   0   0   1   0   0   0
10844    2010   0   0   0   0   0   0   0
         2011   0   0   0   0   0   0   0
         2012   0   0   0   0   0   0   0
         2013   0   0   0   0   0   0   0
10846    2010   0   0   0   0   0   0   0
         2011   1   0   0   1   0   0   1
         2012   0   0   0   0   0   0   0
         2013   0   0   0   1   0   0   0
10856    2010   0   0   0   0   0   0   0
         2011   0   0   0   0   0   0   0
         2012   0   1   0   0   0   0   0
         2013   0   2   0   0   1   0   0
10858    2010   0   0   0   0   0   0   1
         2011   0   1   0   0   0   0   0
         2012   0   0   0   0   0   0   0
         2013   0   0   0   0   0   0   0
10937    2010   0   0   0   0   0   0   0
         2011   0   0   0   0   0   0   0
...            ..  ..  ..  ..  ..  ..  ..
560492   2012   0   0   1   0   1   1   0
         2013   0   0   0   0   1   0   0
560501   2010   0   0   0   0   0   0   0
         2011   0   0   0   0   0   0   0
         2012   0   0   0   0   0   0   0
560508   2010   0   0   0   0   0   0   0
         2011   0   0   0   0   0   1   0
         2012   0   0   0   0   0   0   0
         2013   0   0   0   0   0   0   0
560525   2010   0   0   0   0   0   0   0
         2011   0   0   0   0   0   0   0
         2012   0   0   0   0   0   0   0
         2013   0   0   0   0   0   0   0
560529   2010   0   0   0   1   0   0   0
         2011   0   0   0   0   0   0   0
         2012   0   0   0   1   0   0   0
         2013   1   0   0   0   0   0   0
564121   2010   0   0   0   0   0   0   0
571086   2010   0   0   0   0   0   0   0
         2011   0   0   0   0   0   0   0
         2012   0   0   0   0   0   0   0
         2013   0   0   1   0   0   0   0
574010   2010   0   1   0   0   0   0   0
         2011   0   0   0   0   0   0   0
         2012   0   0   0   0   0   0   0
         2013   0   0   0   0   0   0   0
580996   2010   0   0   0   0   0   1   0
         2011   0   0   0   0   0   0   0
         2012   0   1   1   0   0   0   0
         2013   0   0   0   0   0   0   0

[1325 rows x 27 columns]

In [102]:
dfr = dfx.reset_index()
dfr.columns =  dfr.columns.droplevel()
dfr.columns = ['oshpd_id','year'] + list(dfr.columns)[2:]
dfr.head()

,oshpd_id,year,001,003,004,005,014,765,766,767,...,780,781,782,981,982,983,987,988,989,998
0,10735,2010,0,0,0,0,0,0,0,0,...,0,6,0,0,0,0,0,0,0,0
1,10735,2011,0,0,0,0,0,0,0,0,...,0,5,0,0,0,0,0,0,0,0
2,10735,2012,0,0,0,0,0,0,0,0,...,0,3,0,0,0,0,0,0,0,0
3,10735,2013,0,0,0,0,0,0,0,0,...,0,5,0,0,0,0,0,0,0,0
4,10739,2010,0,0,1,0,0,960,1135,234,...,16,362,90,0,1,0,1,2,0,0